/* Pinnakle Media — case-study site data
   All figures trace to client dashboards, weekly reports, payment records or
   the Aug-2024 case-study file. Photos: assets/clients/<slug>.jpg (colour). */
window.PM = (() => {
  const C = {
    'sold-by-seller':   { name: 'Jonathan · Sold By Seller', short: 'Sold By Seller', niche: 'E-commerce · MRR course', platform: 'Instagram + YouTube', subs: '305 course sales · $150K+', since: 'Jun 2023', until: 'Oct 2023', channel: 'https://www.instagram.com/soldbyseller/' },
    'truthseekah':      { name: 'TruthSeekah & Arien', short: 'TruthSeekah', niche: 'Spiritual podcast', platform: 'YouTube Shorts', subs: '132K subscribers · 4 viral Shorts', since: 'Aug 2024', until: 'Mar 2025', channel: 'https://www.youtube.com/@TruthSeekah' },
    'crypto-giant':     { name: 'Crypto Giant', short: 'Crypto Giant', niche: 'Crypto news', platform: 'YouTube', subs: '61K subscribers · +615% views', since: 'Jul 2024', until: 'Sep 2024', channel: 'https://www.youtube.com/@crypto_giant' },
    'dudley':           { name: 'Dudley J. Edouard', short: 'Dudley J. Edouard', niche: 'Lifestyle · masculinity', platform: 'YouTube', subs: '30K subscribers · 0 → 12K with us', since: 'Jan 2024', until: 'Jul 2024', channel: 'https://www.youtube.com/@DudleyJEdouard' },
    'bkbq':             { name: 'Nicky & Dean · BKBQ Podcast', short: 'BKBQ Podcast', niche: 'Podcast', platform: 'Instagram + YouTube', subs: '66.5K subscribers · 4 of 8 viral', since: 'Nov 2023', until: '2024', channel: 'https://www.instagram.com/bkbqpodcast/' },
    'selected-investments': { name: 'Selected Investments', short: 'Selected Investments', niche: 'Crypto · finance', platform: 'YouTube', subs: '61K subscribers · 10–50× views', since: 'May 2023', until: 'Dec 2023', channel: 'https://www.youtube.com/@SelectedCryptoInvestments' },
    'kryptoplaygirl':   { name: 'Kryptoplaygirl', short: 'Kryptoplaygirl', niche: 'Crypto', platform: 'TikTok', subs: '0 → 3.4K TikTok in 6 weeks', since: 'Jun 2024', until: 'Aug 2024', channel: 'https://www.tiktok.com/@kryptoplaygirl' },
    'gnr-podcast':      { name: 'GNR Podcast', short: 'GNR Podcast', niche: 'Self-development · books', platform: 'YouTube, TikTok, IG', subs: '55K subscribers · 40K views in a day', since: 'Jun 2024', until: 'Dec 2024', channel: 'https://www.youtube.com/@GNRPodcast', slug: 'gnr-podcast', photo: 'assets/clients/gnr-podcast.jpg' },
    'rc-with-adam':     { name: 'Adam Stokes · RC with Adam', short: 'RC with Adam', niche: 'Podcast · personal growth', platform: 'YouTube, LinkedIn', subs: 'LinkedIn launch · 10K reach in month one', since: 'Sep 2024', until: '2025', channel: 'https://www.youtube.com/channel/UCOI2RK-MDHtsBzz9IX_6F1w', slug: 'rc-with-adam', photo: 'assets/clients/rc-with-adam.jpg' },
    'digital-income-project': { name: 'Clay · Digital Income Project', short: 'Digital Income Project', niche: 'Digital products · online income', platform: 'YouTube, Instagram', subs: 'Digital-product education channel', since: '2025', until: 'today', channel: 'https://www.youtube.com/@DigitalIncomeProject', slug: 'digital-income-project', photo: 'assets/clients/digital-income-project.jpg' },
    'hiz-herz':         { name: 'Quincy Brown Sr · Hiz & Herz Perspective', short: 'Hiz & Herz', niche: 'Relationships · motivation', platform: 'YouTube, Facebook', subs: '20K subscribers · +122% in a week', since: 'Sep 2024', until: 'today', channel: 'https://www.youtube.com/@HizandHerzPerspective' },
    'retipster':        { name: 'Seth Williams · REtipster', short: 'REtipster', niche: 'Land investing education', platform: 'YouTube, IG, FB, TikTok', subs: '151K subscribers · since 2024', since: 'Sep 2024', until: 'today', channel: 'https://www.youtube.com/@REtipster' },
    'financial-controller': { name: 'Bill Hanna · The Financial Controller', short: 'The Financial Controller', niche: 'Accounting education', platform: 'YouTube, LinkedIn', subs: '348K subscribers', since: 'Jul 2024', until: 'today', channel: 'https://www.youtube.com/@TheFinancialController' },
    'yoshi':            { name: 'Yogashri “Yoshi” Pradhan', short: 'Yoshi Pradhan', niche: 'Energy leader · author', platform: 'LinkedIn, YouTube', subs: '~31K LinkedIn followers', since: 'Jan 2025', until: 'today', channel: 'https://www.youtube.com/@yogashripradhan' },
    'foyr':             { name: 'Foyr Neo', short: 'Foyr Neo', niche: 'Interior-design SaaS (B2B)', platform: 'YouTube, Instagram, LinkedIn', subs: '44.5K subscribers · B2B SaaS', since: 'Nov 2024', until: 'today', channel: 'https://www.youtube.com/@foyrneo' },
    'thrivewell':       { name: 'The ThriveWell Journey Podcast', short: 'ThriveWell', niche: 'Business & faith podcast', platform: '7 platforms', subs: '20K subscribers · +4.7K in month one', since: 'Nov 2025', until: 'today', channel: 'https://www.youtube.com/@thethrivewelljourney' },
    'elijah-eagle':     { name: 'Elijah Eagle · Hour of His Glory', short: 'Elijah Eagle', niche: 'Christian coaching', platform: 'YouTube, IG, FB, Skool', subs: '40 → 81 subs / week', since: 'Aug 2025', until: 'today', channel: '' },
    'steve-karrasch':   { name: 'Steve & Meghan Karrasch · Karrasch Real Properties', short: 'Karrasch Real Properties', niche: 'Canadian real estate', platform: 'YouTube', subs: '20K subscribers · client since 2022', since: 'Dec 2022', until: 'today', channel: 'https://www.youtube.com/@SteveKarrasch' },
    'canada-couple':    { name: 'Canada Couple', short: 'Canada Couple', niche: 'Vlog', platform: 'YouTube', subs: '882K subscribers', since: '2023', until: '', channel: 'https://www.youtube.com/@CanadaCoupleVlogs' },
    'marcellus-wiley':  { name: 'Marcellus Wiley', short: 'Marcellus Wiley', niche: 'Sports · ex-NFL', platform: 'YouTube, Instagram', subs: '572K subscribers · ex-NFL', since: 'Jul 2024', until: 'Sep 2024', channel: 'https://www.youtube.com/@marcelluswileydatdude' },
    'levi':             { name: 'Levi Rietveld · Levi Crypto', short: 'Levi Crypto', niche: 'Crypto', platform: 'YouTube, TikTok', subs: '233K subscribers · first client, 2022', since: 'Dec 2022', until: 'Nov 2023', channel: 'https://www.youtube.com/@LeviCrypto' },
    'wealth-nation':    { name: 'Wealth Nation', short: 'Wealth Nation', niche: 'Personal finance', platform: 'YouTube', subs: '205K subscribers', since: '2024', until: '', channel: 'https://www.youtube.com/@WealthNation' },
    'cryptojack':       { name: 'CryptoJack', short: 'CryptoJack', niche: 'Crypto', platform: 'YouTube', subs: '253K subscribers', since: 'Nov 2024', until: 'today', channel: '' },
    'smart-money-circle': { name: 'Adam Sarhan · Smart Money Circle', short: 'Smart Money Circle', niche: 'Finance podcast', platform: 'YouTube', subs: '79K subscribers', since: 'Dec 2024', until: 'Jan 2025', channel: 'https://www.youtube.com/@smartmoneycircleshowhosted6940' },
    'brad-mccallum':    { name: 'Brad McCallum', short: 'Brad McCallum', niche: 'Real estate', platform: 'YouTube', subs: '53K subscribers · Calgary realtor', since: '2023', until: '', channel: 'https://www.youtube.com/@BradMcCallum' },
    'classy-crypto':    { name: 'Classy Crypto (Jesus Martinez)', short: 'Classy Crypto', niche: 'Crypto', platform: 'YouTube', subs: '37K subscribers', since: 'Dec 2022', until: '', channel: 'https://www.youtube.com/@ClassyCryptoYT' },
    'grief-2-growth':   { name: 'Brian D. Smith · Grief 2 Growth', short: 'Grief 2 Growth', niche: 'Grief coaching', platform: 'YouTube, LinkedIn, IG', subs: '18.5K subscribers', since: 'Nov 2024', until: '2025', channel: 'https://www.youtube.com/@Grief2Growth' },
    'tom-storey':       { name: 'The Tom Storey Show', short: 'Tom Storey', niche: 'Real estate podcast', platform: 'YouTube', subs: '8.9K subscribers · real estate', since: 'Dec 2022', until: '', channel: 'https://www.youtube.com/@TheTomStoreyShow' },
    'school-of-personal-finance': { name: 'Richard · School of Personal Finance', short: 'School of Personal Finance', niche: 'Finance education', platform: 'YouTube', subs: '71K subscribers', since: 'Nov 2023', until: '2024', channel: 'https://www.youtube.com/@SchoolofPersonalFinance' },
    'marco-torres':     { name: 'Marco Torres · Marketing Boost', short: 'Marketing Boost', niche: 'Marketing · SaaS', platform: 'YouTube, Instagram', subs: '308 videos delivered', since: 'Jul 2025', until: 'today', channel: '' },
    'jon-law':          { name: 'Jon Law', short: 'Jon Law', niche: 'AI tools · business', platform: 'YouTube', subs: '1.12M subscribers', since: 'Aug 2025', until: '2026', channel: 'https://www.youtube.com/@jonlawedu' },
    'anshul-kumar':     { name: 'Anshul Kumar', short: 'Anshul Kumar', niche: 'Productivity · AI', platform: 'YouTube, Instagram', subs: '62K subscribers', since: 'Oct 2025', until: '2026', channel: '' },
    'serena':           { name: 'Serena Musick · Purely Tallow', short: 'Purely Tallow', niche: 'DTC skincare · carnivore', platform: 'Instagram, YouTube', subs: '58K subscribers · DTC skincare', since: 'Aug 2025', until: 'today', channel: 'https://www.instagram.com/purelytallowskincare/' },
    'courtney-luna':    { name: 'Courtney Luna', short: 'Courtney Luna', niche: 'Carnivore diet · vlogs', platform: 'YouTube, Facebook', subs: '127K subscribers', since: 'Sep 2025', until: 'today', channel: 'https://www.youtube.com/c/courtneyluna' },
    'veronica-monet':   { name: 'Veronica Monet · The Shame Free Zone', short: 'Veronica Monet', niche: 'Relationships · healing', platform: 'YouTube, Facebook', subs: '5/5 TidyCal review', since: 'May 2026', until: 'today', channel: 'https://www.youtube.com/@VeronicaMonet' },
    'ryan-making-money-simple': { name: 'Ryan · Making Money Simple', short: 'Making Money Simple', niche: 'UK personal finance · author', platform: 'YouTube', subs: '15K subscribers · UK finance', since: 'May 2026', until: 'today', channel: '' },
    'charente-carr':    { name: 'Charente Carr · JCLV 21', short: 'Charente Carr', niche: 'Lifestyle vlogs · VidCon', platform: 'YouTube', subs: '537K subscribers', since: 'Dec 2024', until: '2026', channel: 'https://www.youtube.com/@CharenteC' },
    'sabby-sabs':       { name: 'Sabrina Salvati · Sabby Sabs', short: 'Sabby Sabs', niche: 'Political commentary', platform: 'YouTube', subs: '423K subscribers', since: 'Jan 2025', until: '2026', channel: 'https://www.youtube.com/@SabbySabs' },
    'debbi-dimaggio':   { name: 'Debbi DiMaggio', short: 'Debbi DiMaggio', niche: 'Real estate · speaker', platform: 'YouTube', subs: '9K subscribers', since: 'Sep 2025', until: '2026', channel: 'https://www.youtube.com/@DebbiDiMaggio' },
    'kiana-danial':     { name: 'Kiana Danial · Invest Diva', short: 'Invest Diva', niche: 'Investing education', platform: 'YouTube', subs: '76K subscribers', since: 'Oct 2025', until: '', channel: '' },
    'laurie':           { name: 'Laurie Denomme · Water Exercise Coach', short: 'Water Exercise Coach', niche: 'Fitness', platform: 'YouTube', subs: '34K subscribers · +1,000 / month', since: 'Jul 2024', until: 'Nov 2024', channel: '' },
    'howard-sambol':    { name: 'Howard Sambol · Life Crafting', short: 'Life Crafting', niche: 'Coaching · Astro Dice', platform: 'YouTube, IG, FB', subs: 'Channel revamp', since: 'Jul 2026', until: 'Aug 2026', channel: 'https://www.youtube.com/@LifeCraftingProgram' },
    'amber-davis':      { name: 'Pastor Amber Davis · Living in Victory', short: 'Pastor Amber Davis', niche: 'Ministry', platform: 'YouTube, IG, FB', subs: '8.7K subscribers', since: 'Jul 2025', until: '2026', channel: '' },
    'gothic-mystic':    { name: 'Joshua · The Gothic Mystic', short: 'The Gothic Mystic', niche: 'Christian YouTube', platform: 'YouTube', subs: '', since: 'Mar 2025', until: 'Jun 2025', channel: '' },
    'matt-young':       { name: 'Mystic Matt Young', short: 'Matt Young', niche: 'Healer · tarot', platform: 'Instagram', subs: '', since: 'Feb 2026', until: '2026', channel: '' },
    'david-meltzer':    { name: 'David Meltzer', short: 'David Meltzer', niche: 'Business · speaker', platform: 'YouTube', subs: '129K subscribers · sample edit', since: 'Feb 2024', until: '', channel: 'https://www.youtube.com/@davidmeltzer' },
    'forbes-riley':     { name: 'Forbes Riley', short: 'Forbes Riley', niche: 'TV · fitness', platform: 'YouTube', subs: '40K subscribers · sample edit', since: 'Nov 2024', until: '', channel: 'https://www.youtube.com/@ForbesRiley' },
    'mr-excel':         { name: 'Bill Jelen · MrExcel', short: 'MrExcel', niche: 'Education · tech', platform: 'YouTube', subs: '169K subscribers · video testimonial', since: 'Mar 2023', until: '', channel: 'https://www.youtube.com/@MrExcel' },
    'iqigai':           { name: 'Iqigai · III Studio · Beet.Health', short: 'III Studio', niche: 'Interior design · health-tech', platform: 'Instagram, LinkedIn', subs: '15 Reels / month', since: 'Nov 2025', until: 'today', channel: '' },
    'printwise':        { name: 'Printwise Global', short: 'Printwise', niche: 'Services · web + social launch', platform: 'Web, IG, FB, LinkedIn', subs: 'Site live in 30 days', since: 'May 2026', until: 'Jul 2026', channel: 'https://www.youtube.com/@print_wise' },
    'millennia-events': { name: 'Millennia Events · Navya Gowda', short: 'Millennia Events', niche: 'Founder meet-ups', platform: 'Web', subs: 'Event website', since: 'Aug 2026', until: 'today', channel: 'https://millennia-founders-meetup.netlify.app' },
    'adam-venture':     { name: 'Adam Venture', short: 'Adam Venture', niche: 'Crypto', platform: 'YouTube', subs: '31K subscribers · video testimonial', since: 'Dec 2022', until: '2023', channel: 'https://www.youtube.com/@AdamVenture' },
    'bryan-guerra':     { name: 'Bryan Guerra', short: 'Bryan Guerra', niche: 'E-commerce · reselling', platform: 'YouTube', subs: '91K subscribers · video testimonial', since: 'May 2023', until: '2023', channel: 'https://www.youtube.com/@BryanGuerra' },
    'dr-lillie-coley':  { name: 'Dr. Lillie M. Coley', short: 'Dr. Lillie Coley', niche: 'Legal advocacy · faith', platform: 'YouTube', subs: '24K subscribers', since: 'May 2025', until: 'Aug 2025', channel: '' },
    'opx-ai':           { name: 'OPX AI', short: 'OPX AI', niche: 'Oil & gas AI', platform: 'YouTube, LinkedIn', subs: '+70% views', since: 'Jan 2026', until: 'Apr 2026', channel: 'https://www.youtube.com/@OPXAI' },
  };
  Object.keys(C).forEach(k => { C[k].slug = k; C[k].photo = `assets/clients/${k}.jpg`; });

  /* Marquee order (most recognisable first) */
  const marquee = ['canada-couple','jon-law','marcellus-wiley','charente-carr','financial-controller','sabby-sabs','cryptojack','levi','wealth-nation','retipster','truthseekah','crypto-giant','smart-money-circle','brad-mccallum','gnr-podcast','classy-crypto','hiz-herz','steve-karrasch','grief-2-growth','foyr','thrivewell','yoshi','courtney-luna','serena','anshul-kumar','mr-excel','david-meltzer','bryan-guerra','veronica-monet','marco-torres','elijah-eagle','kiana-danial','debbi-dimaggio','tom-storey','laurie','printwise'];

  const cases = [
    { slug:'sold-by-seller', theme:'money', size:'wide', tag:'Jun – Oct 2023', big:'$150K', unit:'+ revenue', title:'305 sales of a $499 course in two weeks, from a brand-new Instagram page.',
      desc:'Jonathan launched a fresh account to sell his MRR course. We owned the SEO angle on “MRR”, produced three Shorts every day and built a commission-based partnership. The page converted 305 buyers in its first fortnight, and the partnership extended to 14 of his own customers’ channels, all edited by Pinnakle.',
      chips:[['305 course sales','up'],['3 Shorts / day',''],['14 sub-clients','brand'],['Commission model','']], spark:[2,3,5,9,14,22,31,40,52,61] ,
      did:['SEO on the “MRR” keyword','3 Shorts a day for 2 weeks, then ongoing','Commission-based partnership','Editing for 14 of Jonathan’s own customers (Aug–Oct 2023)'] },
    { slug:'truthseekah', theme:'midnight', tag:'Aug 2024 – Mar 2025', big:'1.1M', unit:'views', title:'4 of the first 10 Shorts went viral.',
      desc:'1.1M, 600K+, 570K and 540K views. Subscribers climbed from 109K to 115K in seven weeks of curiosity-hook Shorts cut from the podcast.',
      chips:[['+1K subs / week','up'],['30 Shorts / month','']], spark:[1,1,2,2,3,9,14,30,42,55], video:'S2bdlQ0uIwA',
      did:['30 Shorts a month from podcast episodes','Curiosity hooks (“Are unicorns in the Bible?”)','Clips channel long-form, intro and banner','Weekly impact reports'] },
    { slug:'crypto-giant', theme:'proof', size:'wide', tag:'Aug 2024', big:'+615%', unit:'views', title:'YouTube itself flagged it: “Your hard work paid off.”',
      desc:'178,131 views in 28 days against a usual 22–30K. +1,243 subscribers, 9.8K watch-hours and $829 estimated revenue, with one video alone clearing 37K views. Long-form and Shorts edited by Pinnakle, listed as channel editor.',
      chips:[['178K views / 28 d','up'],['+1,243 subs','up'],['$829 est. revenue','money']], proof:'assets/proof/crypto-giant-panel.jpg', proof2:'assets/proof/crypto-giant-37k-panel.jpg', spark:[3,3,4,3,5,8,12,20,28,36],
      did:['Long-form and Shorts editing','Thumbnails','Channel-editor access, YouTube Studio reporting'] },
    { slug:'dudley', theme:'', tag:'Jan – Jul 2024', big:'0 → 12K', unit:'subs', title:'Closed a stalled 57.9K channel. Restarted from zero. Monetised in month five.',
      desc:'Re-edited the back catalogue, ranked on one keyword first, then shipped 7 Shorts per long video every week. First AdSense payout: $987/month.',
      chips:[['Monetised month 5','money'],['100+ videos','']], spark:[0,1,2,3,5,6,8,9,11,12],
      did:['Re-edited the old channel’s best videos','Keyword-first upload plan','7 Shorts per long video, daily posting','Thumbnail redesign'] },
    { slug:'bkbq', theme:'', tag:'Nov 2023 – 2024', big:'4 of 8', unit:'went viral', title:'235K, 51.2K, 47.8K and 13.6K views from the first eight posts.',
      desc:'Instagram grew from 800 to 2,600 followers on podcast clips alone. Nicky and Dean recorded a video thank-you.',
      chips:[['IG 800 → 2.6K','up'],['Video testimonial','']], spark:[1,1,2,8,9,12,15,19,23,26], testimonial:'bkbq',
      did:['Podcast clip selection','Reels + Shorts editing','Posting cadence'] },
    { slug:'selected-investments', theme:'cream', tag:'May – Dec 2023', big:'10–50×', unit:'views', title:'Same channel, same host, new editor.',
      desc:'Shorts that had been flat under the previous editor jumped ten to fifty times once topic selection and cut structure changed. Video testimonial on file.',
      chips:[['10–50× Shorts views','up'],['Video testimonial','']], spark:[1,1,1,2,6,12,18,26,38,50], testimonial:'EfHn0koliq0',
      did:['Topic selection from the long-form library','Retention-first Shorts cuts','Weekly delivery'] },
    { slug:'kryptoplaygirl', theme:'', tag:'Jun – Aug 2024', big:'0 → 3.4K', unit:'followers', title:'A brand-new TikTok account to 3,400 followers in six weeks.',
      desc:'30+ Shorts on a consistent daily cadence, cut for TikTok’s first-second retention.',
      chips:[['6 weeks','up'],['30+ Shorts','']], spark:[0,1,3,6,10,15,20,25,30,34],
      did:['Daily TikTok cadence','First-second hooks','Trend-aware sound selection'] },
    { slug:'gnr-podcast', theme:'', tag:'Jun – Dec 2024', big:'40K', unit:'views in a day', title:'Short-form turned a quiet channel into a 3M-view one.',
      desc:'After we added Shorts and every-platform posting, a TikTok clip hit 40K views in 24 hours and the channel added +846 subscribers in a single week. Weekly reports tracked 13.1M impressions at 4.3% CTR.',
      chips:[['+846 subs / week','up'],['3.0M channel views','']], spark:[2,2,3,3,4,6,9,14,20,30],
      did:['30–40 Shorts a month','Posting on YouTube, Instagram, Facebook, TikTok','Weekly Video Impact Reports'] },
    { slug:'hiz-herz', theme:'', tag:'Sep 2024 – today', big:'+122%', unit:'views in a week', title:'Two years in, still finding new angles.',
      desc:'In spring 2026 a celebrity-commentary hook lifted views 122% and engagement 231% in a single week, then 89% the week after. In August 2026 a Facebook Reel hit 44K views. 150+ Shorts delivered for Quincy Brown Sr and counting.',
      chips:[['44K-view Reel','up'],['+231% engagement','up'],['Weekly reports','']], spark:[2,2,3,3,4,5,9,12,16,22], link:'https://www.facebook.com/share/r/1Jxxb8nEY6/',
      did:['15–19 Shorts a month, scripted and repurposed','Celebrity-hook format','Thumbnails and banner','Weekly Strategy / Implementation / Result reports','2026: channel rebuild with personalised AI avatars'] },
    { slug:'retipster', theme:'', tag:'Sep 2024 – today', big:'+41%', unit:'engagement', title:'229 deliverables from a 280-episode podcast library.',
      desc:'Hook rewrites and posting-time changes lifted engagement 41%. A 10-part “Land Myths” series lifted views 17% and engagement 32% in a week. In 2026 Seth handed us upload access to his new channel within a day of launching it.',
      chips:[['229 videos delivered','up'],['2+ year partner','']], spark:[3,3,4,4,5,5,6,7,8,10], video:'CNwyLKhj0l8',
      did:['10–20 Shorts a month across YouTube, IG, FB, TikTok','Series formats and posting-time tests','Monthly analytics reports','Open Voice Labs brand kit and launch (2026)'] },
    { slug:'financial-controller', theme:'', tag:'Jul 2024 – today', big:'8K–42K', unit:'per Short', title:'Shorts, long-form, LinkedIn carousels and a website, for two years.',
      desc:'Shorts routinely land between 8K and 42K views (best 42,287) on a 342K-subscriber channel. Bill recorded a video testimonial in November 2024 and signed a website redesign in March 2026.',
      chips:[['342K subscribers','up'],['Video testimonial','']], spark:[4,5,5,6,8,9,12,15,20,42], testimonial:'y_T-ONr1RuY',
      did:['2 Shorts a week from long-form','HeyGen avatar trained (May 2025)','LinkedIn posts and carousels','Framer website redesign (2026)'] },
    { slug:'yoshi', theme:'', tag:'Jan 2025 – today', big:'365K', unit:'impressions / 28 d', title:'106+ ghostwritten LinkedIn posts, ~31K followers, and a published author.',
      desc:'LinkedIn ghostwriting plus AI-avatar Shorts (HeyGen + ElevenLabs). Impressions rose from 286K to 365K a month; per-post impressions +46% over 90 days. By June 2025 Yoshi had “my first two clients”, a 150-attendee masterclass and a city leadership programme. Video testimonial on file.',
      chips:[['~31K followers','up'],['AI avatar Shorts','']], spark:[20,22,24,26,28,29,31,33,35,36], testimonial:'805KmIDmzNo', video:'mwu9XolFloM',
      did:['LinkedIn ghostwriting (Zaid), 30+ posts a month','HeyGen + ElevenLabs avatar Shorts','Thumbnails, website, Linktree, email automation','2026: OPX AI channel and personal restart'] },
    { slug:'foyr', theme:'cream', tag:'Nov 2024 – today', big:'5 → 17', unit:'videos / month', title:'An enterprise marketing team that tripled its order with us.',
      desc:'Started at five or six videos a month. By April 2026 the Foyr team was commissioning 12 to 17: reels, long-form tutorials, testimonial films, AI street-interview ads, newsletters and carousels. 200+ deliverables logged.',
      chips:[['200+ deliverables','up'],['Design + video + AI','']], spark:[5,6,6,8,9,11,12,14,15,17],
      did:['Long-form tutorials and product comparisons','Reels and ad creatives (9:16 + 1:1)','Testimonial interview films','AI street-interview ads, HeyGen explainers','Carousels, newsletters, landing pages'] },
    { slug:'thrivewell', theme:'', tag:'Nov 2025 – today', big:'+4.7K', unit:'subs in month one', title:'Crossed 15K subscribers five weeks after onboarding.',
      desc:'Full episode edits, 16–20 Shorts, clips, thumbnails A/B-tested and distribution to seven platforms every week. “Thank you all for the great work that you do. It is deeply appreciated.” Video testimonial recorded Jan 2026.',
      chips:[['15K subscribers','up'],['7 platforms',''],['Video testimonial','']], spark:[10,10,11,12,13,14,15,15,15,16],
      did:['4 full podcast edits a month','16–20 Shorts + 6–8 long clips','A/B thumbnails, RSS upload, clips channel','Distribution to YouTube, IG, FB, LinkedIn, X, TikTok, Pinterest'] },
    { slug:'elijah-eagle', theme:'', tag:'Aug 2025 – today', big:'40 → 81', unit:'subs / week', title:'Weekly subscriber growth nearly doubled inside the first month.',
      desc:'Three Shorts a day Monday to Friday, long-form on alternate days, a HeyGen avatar trained on Elijah, and a Skool funnel. First YouTube ad payout of ~$700 by September 2025; a Meta ad reached 31K people with 3.1K clicks. Video testimonial recorded Nov 2025.',
      chips:[['15 Shorts / week','up'],['31K ad reach','up'],['~$700 first payout','money']], spark:[40,44,50,55,60,66,70,75,78,81],
      did:['15 Shorts a week + 3 long-form','HeyGen avatar, brand guidelines','Skool funnel and content strategy (Jan 2026)','Meta ads'] },
    { slug:'steve-karrasch', theme:'cream', tag:'Dec 2022 – today', big:'4 yrs', unit:'every Wednesday', title:'Our longest-running client. One Short a week, never missed.',
      desc:'150+ Shorts cut from Steve’s long-form videos since our Cut To Pro days. A dozen “Love it!” replies on file, a rate increase Meghan agreed to herself in November 2025, and the sample we still show other realtors.',
      chips:[['150+ Shorts','up'],['Since 2022','']], spark:[1,2,3,4,5,6,7,8,9,10],
      did:['One Short every Wednesday from the latest long-form','Frame.io delivery to Meghan for scheduling','Promo reels and ad videos (2023)'] },
  ];

  const wins = [
    ['1.7M','levi','<b>Levi Rietveld · Levi Crypto</b> · our very first client (Dec 2022). Shorts repurposing added 12,000 subscribers in the first two months; best TikTok 1.7M, YouTube Short 555K, Reel 223K. 11-month retainer, then sponsorship management.','Views on one TikTok · +12K subs in two months','2023'],
    ['3×','marcellus-wiley','<b>Marcellus Wiley</b> (335K) · Shorts strategy grew channel views 3× in 90 days; 8 of 12 IG posts and 5 of 8 Shorts beat the channel average, Aug–Sep 2024.','Channel views in 90 days of Shorts','2024'],
    ['88.9K','ryan-making-money-simple','<b>Ryan Hughes</b> (146K on IG) · three Reels earned 88.9K views in one week, Oct 2024.','Views from three Reels in one week','2024'],
    ['4×','wealth-nation','<b>Wealth Nation</b> (196K) · posting cadence jumped from once to four times a week after handing production to Pinnakle.','Posting cadence, once a week to four','2024'],
    ['+1K/mo','laurie','<b>Laurie Denomme · Water Exercise Coach</b> · 18 long-form course videos; 35K monthly views and +1,000 subscribers a month, 2024.','New subscribers a month from 18 course videos','2024'],
    ['14K','school-of-personal-finance','<b>Richard · School of Personal Finance</b> · thumbnail and editing overhaul; a single video reached 14K views and fed his high-ticket coaching. Video testimonial.','Views on one video that fed high-ticket coaching','2024'],
    ['22.7K','iqigai','<b>Dr Jamie · Clay</b> · whiteboard-style Reel hit 22.7K views; 60 Shorts a month plus AI-prompt carousels, 2025–26.','Views on a whiteboard-style Reel · 60 Shorts a month','2025'],
    ['626','jon-law','<b>Jon Law</b> · 626 Shorts delivered on a daily Monday–Friday schedule since Aug 2025. Our highest-volume account.','Shorts delivered, five a week, our biggest account','2025'],
    ['22','serena','<b>Serena Musick · Purely Tallow</b> · 22 customer testimonials turned into Shorts in a single month (Jun 2026), on top of 24-Short product batches and a founder film in her cloned voice.','Customer testimonials cut into Shorts in one month','2026'],
    ['15/mo','iqigai','<b>III Studio &amp; Beet.Health</b> · 15 interior-design Reels a month plus carousels and statics; a client that left and came back.','Interior-design Reels a month · a client who came back','2026'],
    ['9 + 20','courtney-luna','<b>Courtney Luna</b> · contracted for 5 long videos and 12 Shorts, received 9 long videos and 20 Shorts. Came back for a second run in Aug 2026.','Long videos + Shorts delivered on a 5 + 12 contract','2025'],
    ['10K → 17K','grief-2-growth','<b>Brian D. Smith · Grief 2 Growth</b> · subscribers grew 70% across Shorts, thumbnails, LinkedIn and Meta ads (Nov 2024 → mid-2025). “The videos are top notch.”','Subscribers in eight months · “top notch”','2025'],
    ['5 leads','thrivewell','<b>FAYEWAY Media · L. Michael Burt</b> · first ad creative produced five qualified leads on day one; a $40 test spend returned seven (Jun 2026).','Qualified leads on day one of the first ad creative','2026'],
    ['2 yrs','hiz-herz','<b>Quincy Brown Sr · Hiz &amp; Herz</b> · 15 Shorts a month since Sep 2024; in Sep 2026 we’re rebuilding his channel with personalised AI avatars at up to 35 videos a month.','Of 15 Shorts a month · now rebuilding with AI avatars','2026'],
    ['5×','grief-2-growth','<b>Brian D. Smith · LinkedIn</b> · post impressions rose five-fold and followers doubled in the first month of our LinkedIn programme (Jan 2025): 34 posts in 26 days, 60–70 comments a day.','LinkedIn impressions in month one · followers doubled','2025'],
    ['10K','rc-with-adam','<b>Adam Stokes · RC with Adam</b> · a LinkedIn profile launched from zero reached 10K people and 120+ followers in its first 30 days (Dec 2024).','LinkedIn reach in 30 days from a brand-new profile','2024'],
    ['+230%','anshul-kumar','<b>Anshul Kumar</b> · views up 230% and watch time up 281% in one April 2026 week after a Shorts-plus-carousel reset; 66% of Instagram reach from non-followers.','Views in a week after a Shorts + carousel reset','2026'],
    ['+32%','retipster','<b>REtipster · “Land Myths” series</b> · a 10-part Shorts series lifted views 17% and engagement 32% week-on-week (Oct 2025).','Engagement from a 10-part “Land Myths” series','2025'],
    ['+70%','opx-ai','<b>OPX AI</b> · YouTube views up 70% and Instagram interactions from a 2–3 baseline to 56 in a week (Apr 2026); 37% non-follower reach.','YouTube views · IG interactions 3 → 56 in a week','2026'],
    ['3','millennia-events','<b>Millennia Events</b> · a full event website designed, built and deployed for the Mysuru Founders Meet-Up (Aug–Sep 2026), plus reels and posters for three editions.','Event editions: website, reels and posters shipped','2026'],
    ['30 days','printwise','<b>Printwise Global</b> · website, socials, flyers, LinkedIn and Facebook lead-gen launched in 30 days; first inbound leads by week three (Jun 2026).','From zero to website, socials and inbound leads','2026'],
  ];

  const timeline = [
    { year:'2022', label:'Nov – Dec', title:'Cut To Pro is born', text:'Jayanth M B and Prateek Kumar Tiwari start cold-emailing creators with free sample edits. First editor-hiring form goes out on 7 December. First clients: Levi Rietveld, Tom Storey, Adam Venture, Classy Crypto and Karrasch Real Properties, who still receive a Short every Wednesday.', stats:[['2','people'],['5','first clients'],['6 Dec','founded']], chips:['Sample-first outreach','Levi Crypto','Karrasch (still a client)'], clients:['levi','steve-karrasch','tom-storey','classy-crypto'] },
    { year:'2023', label:'The breakout year', title:'First testimonials, first $150K result, and a new name', text:'Mr. Excel, Adam Venture and Bryan Guerra record the first video testimonials. The Sold By Seller partnership generates $150K+ in course sales and 14 sub-clients. In September the brand becomes Pinnakle Media, with the peak-and-arrow mark. PKJMB Media Pvt Ltd is incorporated on 22 December.', stats:[['$150K+','client revenue'],['14','sub-clients'],['Sep','rebrand']], chips:['Rebrand · Sep 2023','$150K+ client revenue','BKBQ · School of Personal Finance'], clients:['sold-by-seller','selected-investments','mr-excel','bkbq','school-of-personal-finance','canada-couple'] },
    { year:'2024', label:'Scale & systems', title:'Viral Shorts and the weekly report', text:'Dudley goes 0 → 12K and monetises. GNR Podcast, Kryptoplaygirl, Marcellus Wiley, Laurie, Crypto Giant (+615%) and TruthSeekah (1.1M-view Short) join. Weekly Video Impact Reports start in September. REtipster, Hiz & Herz, The Financial Controller and Foyr Neo, all still clients in 2026, sign between July and November. A LinkedIn practice opens with Zaid.', stats:[['20','people'],['+615%','best lift'],['1.1M','best Short']], chips:['1.1M-view Short','+615% views','Foyr Neo · Nov 2024','Weekly reports'], clients:['dudley','truthseekah','crypto-giant','marcellus-wiley','gnr-podcast','retipster','hiz-herz','financial-controller','foyr','wealth-nation','rc-with-adam'] },
    { year:'2025', label:'Full channel ops', title:'From editing to running the channel', text:'pinnaklemedia.com launches. ~120 free sample edits convert prospects into retainers. Packages expand to scripting, thumbnails, posting to seven platforms, LinkedIn ghostwriting and AI-avatar video. Yoshi Pradhan, Marco Torres, Jon Law, Serena, Anshul Kumar, ThriveWell, Elijah Eagle, Debbi DiMaggio and Kiana Danial come on board.', stats:[['~120','sample edits'],['7','platforms'],['17','people']], chips:['14+ retainers','AI avatar video','LinkedIn ghostwriting'], clients:['yoshi','marco-torres','jon-law','serena','anshul-kumar','thrivewell','elijah-eagle','debbi-dimaggio','charente-carr','grief-2-growth'] },
    { year:'2026', label:'AI-first studio', title:'Six editors, a QC layer, an AI production pipeline', text:'An in-house QC owner reviews every cut before delivery. Editors earn growth bonuses tied to client views. The studio adds design retainers (III Studio, Beet.Health, Iqigai), a marketing system for a DTC skincare brand, an AI-carousel engine, LinkedIn and web builds (Millennia Events, Printwise) and an AI documentary pipeline. Ten people in Bengaluru.', stats:[['100+','clients'],['3,000+','videos'],['10','people + QC']], chips:['100+ clients served','3,000+ videos','This page · Sep 2026'], clients:['veronica-monet','ryan-making-money-simple','iqigai','printwise','millennia-events','howard-sambol','opx-ai','courtney-luna'] },
  ];

  /* Video testimonials (yt = YouTube id, mp4 = self-hosted) */
  const videoTestimonials = [
    { yt:'EfHn0koliq0', client:'selected-investments', orient:'portrait', title:'“10 to 50× the views on our Shorts.”', meta:'Client May–Dec 2023 · recorded Jan 2024' },
    { yt:'3dZ4XD2wuMM', client:'school-of-personal-finance', orient:'landscape', title:'Richard, School of Personal Finance', meta:'Thumbnails + editing overhaul · Jan 2024' },
    { mp4:'assets/video/bkbq-testimonial.mp4', poster:'assets/video/bkbq-poster.jpg', client:'bkbq', orient:'portrait', title:'Nicky & Dean, BKBQ Podcast', meta:'4 of 8 clips viral · IG 800 → 2.6K · Mar 2024' },
    { yt:'805KmIDmzNo', client:'yoshi', orient:'portrait', title:'Yoshi Pradhan, energy leader & author', meta:'LinkedIn ghostwriting + AI-avatar Shorts · since Jan 2025' },
    { yt:'y_T-ONr1RuY', client:'financial-controller', orient:'landscape', title:'Bill Hanna, The Financial Controller', meta:'342K-subscriber channel · client since 2024' },
    { yt:'vqWtlqUQ9bc', client:'elijah-eagle', orient:'landscape', title:'Elijah Eagle, Hour of His Glory', meta:'15 Shorts a week + long-form · recorded Nov 2025' },
    { yt:'cmra3jv0onM', client:'thrivewell', orient:'portrait', title:'L. Michael Burt, The ThriveWell Journey', meta:'15K → 20K subscribers · recorded Jan 2026' },
    { yt:'ajTPqdk87Ok', client:null, orient:'portrait', title:'A WhatsApp thank-you, unprompted', meta:'Sent to the team, 2025' },
  ];

  /* Written quotes. src: where it came from; date shown as month + year only. */
  const quotes = [
    { c:'retipster', q:'I genuinely appreciate the quality of work you’ve consistently delivered, particularly with the video editing and thumbnail support… the quality of your company’s work, which has been excellent.', who:'Seth Williams', role:'Founder', src:'Email', date:'Oct 2025', star:true },
    { c:'retipster', q:'Going forward, there’s no need to check with me on these. You can just publish them. If I ever see any problems after they’re published, I’ll let you know.', who:'Seth Williams', role:'REtipster · handing over publishing', src:'Slack', date:'Apr 2025', star:true },
    { c:'retipster', q:'Thanks for the update! These metrics are helpful. It’s good to see these kinds of tangible gains.', who:'Seth Williams', role:'REtipster · on a weekly report', src:'Slack', date:'Aug 2025' },
    { c:'retipster', q:'Nice job fitting it all into one minute! That’s impressive.', who:'Seth Williams', role:'REtipster', src:'Slack', date:'Feb 2025' },
    { c:'retipster', q:'As simple as it sounds, I don’t have time to do all of this… Can I pay Pinnakle to handle this task?', who:'Seth Williams', role:'REtipster · expanding the retainer', src:'Slack', date:'Jan 2026' },
    { c:'thrivewell', q:'It’s approved! Thank you all for the great work that you do. It is deeply appreciated.', who:'L. Michael Burt', role:'The ThriveWell Journey Podcast', src:'Slack', date:'Nov 2025', star:true },
    { c:'thrivewell', q:'This was a great clip. Very captivating. I love that it stayed on him. It was a great teaching moment for people to listen to and come away with added value.', who:'L. Michael Burt', role:'The ThriveWell Journey Podcast', src:'Slack', date:'Jan 2026' },
    { c:'thrivewell', q:'Yes, this is awesome. We still have not gotten YouTube monetization yet, that is next, but we are in a good direction. I appreciate all that you do to support this growth.', who:'L. Michael Burt', role:'The ThriveWell Journey Podcast', src:'Slack', date:'Dec 2025' },
    { c:'thrivewell', q:'We love the promo. It looks great and is strong and bold and powerful. Exactly what we are looking for.', who:'Evan Butris', role:'The ThriveWell Journey Podcast', src:'Slack', date:'Jan 2026', star:true },
    { c:'thrivewell', q:'I LOVED the intro. It was fresh and fun.', who:'Evan Butris', role:'The ThriveWell Journey Podcast', src:'Review notes', date:'Jan 2026' },
    { c:'thrivewell', q:'Agreed with Michael. You guys have been wonderful.', who:'Evan Butris', role:'The ThriveWell Journey Podcast', src:'Slack', date:'Nov 2025' },
    { c:'thrivewell', q:'I really like the style of the captions on this video. The graphics are great, and the story can hit home for some people.', who:'Michael', role:'The ThriveWell Journey Podcast', src:'Review notes', date:'Nov 2025' },
    { c:'grief-2-growth', q:'The shorts are excellent. They are extremely well done.', who:'Brian D. Smith', role:'Grief 2 Growth · 10K → 17K subscribers', src:'Email', date:'Jan 2025', star:true },
    { c:'grief-2-growth', q:'As always, your team is doing a fantastic job. The videos are top notch. The communication is excellent.', who:'Brian D. Smith', role:'Grief 2 Growth', src:'Email', date:'Jun 2025' },
    { c:'grief-2-growth', q:'I saw one of the ads you are running for my consulting services and it’s awesome. In fact, I’d like to get a copy of it. So far, I’ve had about four or five people message me on WhatsApp.', who:'Brian D. Smith', role:'Grief 2 Growth · on the Meta ad', src:'Email', date:'Mar 2025' },
    { c:'steve-karrasch', q:'Wow, two years?! Time sure flies! Thank you for getting the last two shorts to me early for scheduling.', who:'Meghan Karrasch', role:'Karrasch Real Properties', src:'Email', date:'Dec 2024', star:true },
    { c:'steve-karrasch', q:'Great short this week! Thanks.', who:'Meghan Karrasch', role:'one of a dozen weekly “Love it!” replies, 2024–2026', src:'Email', date:'Sep 2025' },
    { c:'steve-karrasch', q:'I think our loyalty for 3 years should still warrant a discount… however I do agree that a raise is appropriate.', who:'Meghan Karrasch', role:'agreeing a rate increase after three years', src:'Email', date:'Nov 2025' },
    { c:'yoshi', q:'I may not say this a lot but I want to express my appreciation of how hard you all are working. It’s not easy expanding the business when you are lean.', who:'Yoshi Pradhan', role:'IronLady Energy Advisors', src:'Slack', date:'May 2025', star:true },
    { c:'yoshi', q:'Keep it coming ❤️ I appreciate you.', who:'Yoshi Pradhan', role:'on the LinkedIn posts', src:'Slack', date:'May 2025' },
    { c:'yoshi', q:'700 views in 20 minutes!!! … The latest short crossed over 1,000 views!', who:'Yoshi Pradhan', role:'on two August 2025 Shorts', src:'Slack', date:'Aug 2025' },
    { c:'charente-carr', q:'Thank you so much for all the hard work that you have been doing. I greatly appreciate it.', who:'Charente Carr', role:'JCLV 21', src:'Slack', date:'Oct 2025', star:true },
    { c:'charente-carr', q:'I greatly appreciate each and every single one of you. Thank you!', who:'Charente Carr', role:'JCLV 21', src:'Slack', date:'Jan 2026' },
    { c:'charente-carr', q:'Editing rating went from 3 out of 5 to 5 out of 5.', who:'Charente Carr', role:'status call summary', src:'Call', date:'Aug 2025' },
    { c:'truthseekah', q:'Whoever is doing the editing, great job. The images and moving images and sounds are looking so much better than the last batch. I like how at the end it shows the thumbnail of the podcast the clip came from.', who:'TruthSeekah', role:'129K+ subscribers · relayed by the team', src:'Slack', date:'Jun 2025', star:true },
    { c:'veronica-monet', q:'5 out of 5 stars. Prateek was great!', who:'Veronica Monet', role:'The Shame Free Zone', src:'TidyCal review', date:'May 2026', star:true },
    { c:'foyr', q:'We truly appreciate our ongoing partnership and the work you do for us.', who:'Anushua Nath', role:'Sr Digital Marketing Manager, Foyr', src:'Email', date:'Mar 2026', star:true },
    { c:'marco-torres', q:'We handed them raw footage and got back a system. That’s the difference between an editor and a content team.', who:'Marco Torres', role:'Founder', src:'Partner deck', date:'2026' },
    { c:'anshul-kumar', q:'Nice graphics and design… great style. Just a quick fix on some lines and then good to go!', who:'Anshul Kumar', role:'YouTube creator', src:'Review notes', date:'Sep 2025' },
    { c:'gnr-podcast', q:'Look, the video went viral. I am very happy that you work with all your heart as a team to succeed even more.', who:'GNR Podcast team', role:'on the 40K-views-in-a-day TikTok', src:'WhatsApp', date:'Jul 2024' },
    { c:'rc-with-adam', q:'I see your videos and I find you have such a great dedication towards your work. Your content is very good.', who:'Adam Stokes', role:'Host, RC with Adam', src:'Slack', date:'Sep 2024' },
    { c:'howard-sambol', q:'They’re all fantastic.', who:'Howard Sambol', role:'Founder, Life Crafting · on the first batch of Shorts', src:'Telegram', date:'Jul 2026' },
    { c:'canada-couple', q:'Weekly Shorts system: the channel now runs on autopilot with no editing bottlenecks.', who:'Canada Couple', role:'900K+ subscribers', src:'Partner deck', date:'2026' },
    { c:'sabby-sabs', q:'Looks great, thank you!', who:'Sabrina Salvati', role:'Sabby Sabs · one of 13 approvals on record', src:'Slack', date:'2025' },
    { c:'iqigai', q:'Good to go.', who:'Aditi', role:'the approval we hear most', src:'WhatsApp', date:'2026' },
    { c:'retipster', q:'As long as you make sure I look cool :)', who:'Seth Williams', role:'approving AI footage of himself · Open Voice Labs', src:'Slack', date:'Jul 2026' },
    { c:'financial-controller', q:'Significant improvements in video quality and engagement.', who:'Bill Hanna, CPA', role:'The Financial Controller · status call summary', src:'Call', date:'Apr 2025', star:true },
    { c:'financial-controller', q:'Signed and attached. I will give your team access to Framer.', who:'Bill Hanna, CPA', role:'signing the website redesign', src:'Email', date:'Mar 2026' },
    { c:'hiz-herz', q:'I like the style so far.', who:'Quincy Brown Sr', role:'on the very first Short', src:'Email', date:'Sep 2024' },
    { c:'gothic-mystic', q:'I liked the short. … Videos look good.', who:'Joshua', role:'The Gothic Mystic', src:'Slack', date:'Apr–Jun 2025' },
    { c:'veronica-monet', q:'The long video is good! I asked for one correction for the text at the end.', who:'Veronica Monet', role:'The Shame Free Zone', src:'Slack', date:'Sep 2026' },
    { c:'printwise', q:'Amazing work… Appreciated. All these are leads.', who:'Founder', role:'on the launch month', src:'Slack', date:'Jun 2026' },
    { c:'marcellus-wiley', q:'Great, thank you so much!', who:'Desiree Cross', role:'Director of Digital Strategy, Project Transition · Marcellus Wiley’s team', src:'Email', date:'Sep 2024' },
    { c:'anshul-kumar', q:'Thanks Prateek. Let’s proceed.', who:'Anshul Kumar', role:'renewing for the second phase', src:'Email', date:'Apr 2026' },
  ];

  /* Work samples — YouTube ids (all public, hosted on the Pinnakle Media or client channels) */
  const samples = {
    shorts: [
      { yt:'S2bdlQ0uIwA', client:'truthseekah', title:'Glorifying God through every challenge', views:'456K views', loop:'assets/loops/truthseekah-S2bdlQ0uIwA-loop.mp4', poster:'assets/loops/truthseekah-S2bdlQ0uIwA-loop.jpg' },
      { yt:'l5nlgz3hPMk', client:'truthseekah', title:'Are unicorns in the Bible?', views:'105K views', loop:'assets/loops/truthseekah-l5nlgz3hPMk-loop.mp4', poster:'assets/loops/truthseekah-l5nlgz3hPMk-loop.jpg' },
      { yt:'_1uu58fimFU', client:'anshul-kumar', title:'Stop reading PDFs, AI watches them for you', views:'2.1K views', loop:'assets/loops/anshul-kumar-_1uu58fimFU-loop.mp4', poster:'assets/loops/anshul-kumar-_1uu58fimFU-loop.jpg' },
      { yt:'SpAkYcq6sDI', client:'grief-2-growth', title:'Unprocessed emotions get stuck as energy', views:'1.6K views', loop:'assets/loops/grief2growth-SpAkYcq6sDI-loop.mp4', poster:'assets/loops/grief2growth-SpAkYcq6sDI-loop.jpg' },
      { yt:'H0A-41jYH58', client:'yoshi', title:'Hottest skills in oil & gas right now', views:'1.2K views', loop:'assets/loops/yoshi-pradhan-H0A-41jYH58-loop.mp4', poster:'assets/loops/yoshi-pradhan-H0A-41jYH58-loop.jpg' },
      { yt:'CNwyLKhj0l8', client:'retipster', title:'The real strategy of billionaires', views:'546 views', loop:'assets/loops/retipster-CNwyLKhj0l8-loop.mp4', poster:'assets/loops/retipster-CNwyLKhj0l8-loop.jpg' },
      { yt:'CaOUOgNNw9I', client:'retipster', title:'Types of land investors you must know', views:'1.3K views' },
      { yt:'FseOKJMy4M0', client:'truthseekah', title:'Deep calls unto deep. Find your tribe.', views:'12K views' },
      { yt:'rN7EH1g3Raw', client:'grief-2-growth', title:'You weren’t born broken', views:'1.6K views' },
      { yt:'mwu9XolFloM', client:'yoshi', title:'Top skills for 2026: are you ready?', views:'959 views' },
      { yt:'lM1iwG87ydI', client:null, title:'MrBeast Burger going downhill', loop:'assets/loops/pinnakle-media-lM1iwG87ydI-loop.mp4', poster:'assets/loops/pinnakle-media-lM1iwG87ydI-loop.jpg' },
      { yt:'LcfVsPto7uU', client:null, title:'Dark secret of the Zodiac Killer', loop:'assets/loops/pinnakle-media-LcfVsPto7uU-loop.mp4', poster:'assets/loops/pinnakle-media-LcfVsPto7uU-loop.jpg' },
      { yt:'KdNbe0Yo2A0', client:null, title:'Printify' },
      { yt:'U7yZWQYwE7E', client:'wealth-nation', title:'Wealth Nation promo' },
      { yt:'yfZ8XrYJBvQ', client:null, title:'Daniel Ally' },
    ],
    longs: [
      { yt:'2vQiF8M05aE', client:'levi', title:'Levi Crypto · BlackRock explainer' },
      { yt:'WO3ARHEMU2I', client:'howard-sambol', title:'Life Crafting · The Promise Game explainer' },
      { yt:'sWJGn2R5V1s', client:'retipster', title:'Open Voice Labs · The strange power of trying less' },
      { yt:'yez4aN4-jDo', client:'gothic-mystic', title:'The Gothic Mystic · Does God intervene?' },
      { yt:'w87uUtfoWYo', client:null, title:'Brian C. Sundin · true-crime documentary' },
      { yt:'cdx56oyZx2s', client:null, title:'Amex Points · finance explainer' },
    ],
    thumbs: [
      ['assets/thumbs/net-loss-ebitda.webp','The Financial Controller'],['assets/thumbs/year-end-close.webp','The Financial Controller'],['assets/thumbs/ledger-balance.webp','The Financial Controller'],
      ['assets/thumbs/g2g-love-loss.webp','Grief 2 Growth'],['assets/thumbs/g2g-beyond-death.webp','Grief 2 Growth'],['assets/thumbs/escape-the-lies.webp','Coaching'],
      ['assets/thumbs/ultimate-ride.webp','Moto podcast'],['assets/thumbs/yoga-will-not.webp','Fitness'],['assets/thumbs/jealousy.webp','Relationships'],
    ],
    covers: ['01','02','06','07','12','15','16','20','21','24','10','17'].map(n => `assets/covers/cover_${n}.jpg`),
  };

  const beyond = [
    { title:'Millennia Events website', tag:'Web build · 2026', text:'Designed, built and deployed the Founders Meet-Up site for Millennia Events: ivory-and-gold design, reservations form, payments link, three event editions.', img:'assets/beyond/millennia.jpg', link:'https://millennia-founders-meetup.netlify.app', c:'millennia-events' },
    { title:'AI documentary pipeline', tag:'AI video · 2026', text:'A 64-second animated history mini-doc produced end to end with image-to-video generation, cloned voice-over and score. The template for faceless documentary channels.', video:'assets/beyond/celer.mp4', poster:'assets/beyond/celer.jpg', c:null },
    { title:'AI carousel engine', tag:'Design system · 2026', text:'A production system that turns a brief into a finished, branded carousel with caption, keywords, pinned comment and prompt sheet, packaged as a numbered zip.', img:'assets/beyond/carousel.jpg', c:null },
    { title:'Printwise Global launch', tag:'Web + social · Jun 2026', text:'Website with programmatic city pages and booking tracker, Instagram, Facebook, YouTube and LinkedIn set up, flyers and hiring posts, Facebook-group lead-gen. Live in 30 days.', img:'assets/beyond/printwise.jpg', link:'https://printwiseglobal.com', c:'printwise' },
    { title:'Purely Tallow marketing system', tag:'Strategy + AI · Jul 2026', text:'Buyer-psychology strategy, 30-day calendar, and a “Return to Real” founder film with locked AI personas and a cloned voice for a DTC skincare brand.', img:'assets/covers/cover_24.jpg', c:'serena' },
    { title:'HeyGen avatar channels', tag:'AI avatar · 2025–26', text:'Trained avatars for Elijah Eagle, The Financial Controller, TruthSeekah, Yoshi and Marco Torres so Shorts ship without a camera day.', img:'assets/covers/cover_21.jpg', c:'yoshi' },
  ];

  const team = {
    founders: [
      { name:'Jayanth M B', role:'Co-founder & CEO · Operations, delivery & AI', photo:'assets/team/jayanth.jpg', text:'Electronics & Communication engineer turned AI-first content operator. Grew his own YouTube channel past 100K subscribers (Silver Play Button) before starting the company as a freelance editor in 2022. Runs editing operations, the editor team, Frame.io delivery and QC, plus the AI production stack (HeyGen, ElevenLabs, Higgsfield, n8n). Also built ForThePeople.in, a free civic-data platform.', li:'https://www.linkedin.com/in/jayanth-m-b-18713816b/' },
      { name:'Prateek Kumar Tiwari', role:'Co-founder & MD · Growth & client strategy', photo:'assets/team/prateek.jpg', text:'Jayanth\'s classmate and co-founder since day one (6 Dec 2022). Owns client relationships, sales and strategy, has run 100+ discovery calls with creators since 2024 and leads the LinkedIn, cold-email and brand-content practice. Also co-founder of Founders Fuel Academy, where he has taught 5,000+ founders and creators to build agencies and automate their businesses.', li:'https://www.linkedin.com/in/prateek-kumar-tiwari19/' },
    ],
    now: [
      ['Shreedhi Gupta','Operations & social media manager'],['Darshan Vadhiya','QC lead · editor'],['Navin G','Senior Shorts editor'],['Rahul Kumar','Editor'],['Pritam','Editor'],['Ayush Kumar Gupta','Developer · AI automation'],['Chanmai Khelwar','Design lead'],['Zaid Ahmed','LinkedIn specialist'],['Shrinidhi Vardhan','Brand strategist'],['Vinay','Thumbnails & graphics'],
    ],
    alumni: ['Ruman (editor, 2024–26)','Ritesh Chaudhary (editing manager, 2024–25)','Harsh Giri (designer · built the first website)','Jaya Lohar (operations, 2025)','Yuvraj Saini','Aditya Upadhyay','Aditya Khurana','Sunitha Gautam','Huzaifa Shaikh','Syed','Sachin Kalura','Karan','Rixit','Abhishek','Paras Kumar','Dhananjay','Ikjot','Manan','Raj Paul','Shrishti Chandra','Abhimanyu Kumar','Dilip','Mohit','Aniket Das','Abhinav Tiwari'],
  };


  /* Per-case chart shapes (each case gets its own visual, drawn on scroll) */
  const viz = {
    'sold-by-seller':      { t:'bars', c:'green', d:[1,2,4,7,12,18,22,30,36,41,47,52,56,61], hi:[8,9,10,11,12,13] },
    'truthseekah':         { t:'spike', d:[2,2,3,2,25,3,44,2,38,3,30,2] },
    'dudley':              { t:'step', d:[0,0.5,1.5,3,5,7,9,12], marker:4 },
    'bkbq':                { t:'ratio', n:8, k:4 },
    'selected-investments':{ t:'beforeafter', a:[2,2,3,2,2], b:[20,26,34,42,50] },
    'kryptoplaygirl':      { t:'area', d:[0,1,3,6,10,15,20,25,30,34] },
    'gnr-podcast':         { t:'spike', d:[3,3,4,3,5,4,6,5,40,12,14] },
    'hiz-herz':            { t:'bars', d:[10,11,10,12,11,13,29,25], hi:[6,7] },
    'retipster':           { t:'dual', a:[5,5,6,5,6,6,6], b:[6,7,8,9,9,10,11] },
    'financial-controller':{ t:'dots', d:[8,14,22,10,42,18,30,12,36,26] },
    'yoshi':               { t:'dual', a:[28,29,28,30,29,30], b:[30,32,33,35,36,36.5] },
    'foyr':                { t:'bars', d:[5,6,6,8,9,11,12,14,15,17] },
    'thrivewell':          { t:'area', d:[10,10.4,11,12,13,14,15,15.4,16] },
    'elijah-eagle':        { t:'bars', d:[40,44,50,55,60,66,70,75,81], hi:[6,7,8] },
    'steve-karrasch':      { t:'grid', rows:4, cols:13 },
  };
  /* Receipts: real screenshots, shown inside the client's story (sensitive figures blurred) */
  const receipts = [
    { img:'assets/receipts/yt-grief2growth-year.jpg', src:'YouTube Studio', c:'grief-2-growth', title:'Grief 2 Growth · last 365 days', text:'Watch time +69% and subscribers +129% year on year. Ad revenue figure blurred.' },
    { img:'assets/receipts/yt-thrivewell-year.jpg', src:'YouTube Studio', c:'thrivewell', title:'The ThriveWell Journey · last 365 days', text:'+13.5K subscribers, 111% more than the previous year.' },
    { img:'assets/receipts/email-retipster.jpg', src:'Email', c:'retipster', title:'Seth Williams · Oct 2025', text:'“I genuinely appreciate the quality of work you’ve consistently delivered… which has been excellent.” Budget lines blurred.' },
    { img:'assets/receipts/gnr-whatsapp-1.jpg', src:'WhatsApp', c:'gnr-podcast', title:'GNR Podcast · Jul 2024', text:'“Bro, in TikTok it went to 40K.”' },
    { img:'assets/receipts/gnr-whatsapp-2.jpg', src:'WhatsApp', c:'gnr-podcast', title:'GNR Podcast · Jul 2024', text:'“I am very happy that you work with all your heart as a team.” “Look, the video went viral.”' },
  ];
  const brands = [
    ['foyr','B2B interior-design SaaS'],['financial-controller','The Financial Controller Academy'],['digital-income-project','Digital-product education'],['retipster','Land-investing media company'],
    ['marco-torres','Marketing Boost Solutions'],['iqigai','III Studio · Beet.Health'],['printwise','Printwise Global'],['opx-ai','Oil & gas AI'],['serena','Purely Tallow · D2C skincare'],
    ['howard-sambol','Life Crafting Program'],['grief-2-growth','Grief 2 Growth'],['steve-karrasch','Karrasch Real Properties'],['sold-by-seller','Sold By Seller'],['kiana-danial','Invest Diva'],['millennia-events','Millennia Events'],
  ];
  return { C, marquee, cases, wins, timeline, videoTestimonials, quotes, samples, beyond, team, viz, receipts, brands };
})();
